name: elaser
description: E-laser app for CNC machine
publish_to: 'none'
version: 0.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  easy_localization: ^3.0.3
  dio: ^5.4.0
  provider: ^6.1.1
  get_it: ^7.6.4
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  connection_wrapper:
    path: my_packages/conncection_wrapper


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/translations/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 700